sudo: required
services:
- docker
language: groovy
jdk:
- oraclejdk8
before_install:
- cat /etc/hosts
- sudo hostname "$(hostname | cut -c1-63)"
- sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo
  tee /etc/hosts
- cat /etc/hosts
- docker run -p 6379:6379 -d redis redis-server --appendonly yes
before_script:
- rm -rf target
script: "./travis-build.sh"
after_script:
- docker ps -a -q  --filter ancestor=redis | xargs docker container stop
- docker ps -a -q  --filter ancestor=redis | xargs docker container rm
env:
  global:
  - GIT_NAME="Puneet Behl"
  - GIT_EMAIL="behl4485@gmail.com"
  - secure: 40PjXwv2INK8/Cs5OO5RYUH0YZpHdU0jELyle2BW+2EObiYpUyS4z9DeAHybMsF4sv6pdnyAS7PiGxduo52J8JceHKAhWrn1H/3i8BfGuVWagY8BUmt0f+vl3EoLtTBgps8G0VlkRk09wTYAM2WbsaMLmZ4Lfa5UH8IUBPGyCBI=
  - secure: 2DyB7to+ZFvjqjZvFdnDWjmZBtEnQSC8FZTxwm2xVhWHkvmNauvbkATeoc++fiQLPf+FRO6bCu9J5gV7GM4y3OI5FC5C52j5FDzKtuDK/llrR5s7FH0DFHqV0hCmalxR9m00tvu4z+F4wefAsZOShKPRCxPxNykrOQL24IYXIdc=
